- name: start splunk binary firsttime
  command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd {{ first_time_passwd }}"

- name: wait for splunk to come up
  wait_for:
    port: 8089
    delay: 5
